{% set name = "materials-learning-algorithms" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mala-project/mala/archive/v{{ version }}.tar.gz
  sha256: 4fef961c31449da306a16cc431343a38cbc5092e062c56d9fc2dcd8f9d17d136

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - ase
    - mpmath
    - numpy
    - optuna
    - scipy
    - pandas
    - tensorboard
    - pytorch

test:
  imports:
    - mala
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mala-project/mala
  summary: Materials Learning Algorithms. A framework for machine learning materials properties from first-principles data.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
